keys={
    '0':['q','w','e','r','t','y','u','i','o','p'],
    '1':['a','s','d','f','g','h','j','k','l'],
    '2':['z','x','c','v','b','n','m'],
    'length': 3
}
hash={
    'q':'qq.com',
    'w':'weibo.com',
    't':'taobao.com',
    'z':'zhihu.com'
}
hashLocal=JSON.parse(localStorage.getItem('zzz') || null)
if(hashLocal){
    hash=hashLocal
}
index=0;
//遍历keys
while(index<keys['length']){
    row=keys[index]
    div=document.createElement('div')
    wrapper.appendChild(div)
    index2=0
    //遍历row
    while(index2<row['length']){
        kbd=document.createElement('kbd')
        span=document.createElement('span')
        span.textContent=row[index2]
        span.className='text'
        img=document.createElement('img')
        if(hash[row[index2]]){
            img.src='http://'+hash[row[index2]]+'/favicon.ico'
        }else{
            img.src='https://i.loli.net/2018/04/06/5ac728d851969.png'
        }
        button=document.createElement('button')
        button.textContent='编辑'
        button.id=row[index2]
        kbd.appendChild(span)
        kbd.appendChild(img)
        kbd.appendChild(button)
        div.appendChild(kbd)
        button.onclick=function(aaaa){
            key=aaaa['target']['id']
            x=prompt('给我一个网址')
            hash[key]=x;
            localStorage.setItem('zzz',JSON.stringify(hash))
        }
        index2++
    }


    index++
}
document.onkeypress=function(ssss){
    key=ssss['key']
    if(hash[key]==undefined || hash[key]==''){
        alert('还未设置当前快捷键')
    }else{
        web='http://'+hash[key]
        window.open(web,'_blank')
    }
}